backend:
  name: test-repo
  repo: Hubackova/raseliniste
  branch: master

media_folder: static/assets
public_folder: assets


collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/publications.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
